'use strict';

var React = require('react/addons');

module.exports = {
  // Essence components
  AppBar: require('./components/AppBar').(React),
  BottomSheets: require('./components/BottomSheets').(React),
  BottomSheetsItem: require('./components/BottomSheetsItem').(React),
  Btn: require('./components/Btn').(React),
  BtnItem: require('./components/BtnItem').(React),
  Block: require('./components/Block').(React),
  Card: require('./components/Card').(React),
  CardItem: require('./components/CardItem').(React),
  CardItemHeader: require('./components/CardItemHeader').(React),
  CardItemContent: require('./components/CardItemContent').(React),
  CardItemFooter: require('./components/CardItemFooter').(React),
  Chip: require('./components/Chip').(React),
  ChipItem: require('./components/ChipItem').(React),
  DatePicker: require('./components/DatePicker').(React),
  DatePickerItem: require('./components/DatePickerItem').(React),
  DatePickerHeader: require('./components/DatePickerHeader').(React),
  DatePickerHeaderDay: require('./components/DatePickerHeaderDay').(React),
  DatePickerHeaderDate: require('./components/DatePickerHeaderDate').(React),
  DatePickerContent: require('./components/DatePickerContent').(React),
  DatePickerFooter: require('./components/DatePickerFooter').(React),
  Dialog: require('./components/Dialog').(React),
  DialogItem: require('./components/DialogItem').(React),
  DialogItemHeader: require('./components/DialogItemHeader').(React),
  DialogItemContent: require('./components/DialogItemContent').(React),
  DialogItemFooter: require('./components/DialogItemFooter').(React),
  Divider: require('./components/Divider').(React),
  Icon: require('./components/Icon').(React),
  Image: require('./components/Image').(React),
  Input: require('./components/Input').(React),
  InputItem: require('./components/InputItem').(React),
  List: require('./components/List').(React),
  ListItem: require('./components/ListItem').(React),
  Menu: require('./components/Menu').(React),
  MenuItem: require('./components/MenuItem').(React),
  Navigation: require('./components/Navigation').(React),
  Paper: require('./components/Paper').(React),
  PaperItem: require('./components/PaperItem').(React),
  Progress: require('./components/Progress').(React),
  Slider: require('./components/Slider').(React),
  SliderItem: require('./components/SliderItem').(React),
  Snackbar: require('./components/Snackbar').(React),
  SnackbarItem: require('./components/SnackbarItem').(React),
  Switch: require('./components/Switch').(React),
  SwitchItem: require('./components/SwitchItem').(React),
  TabItem: require('./components/TabItem').(React),
  TabMenu: require('./components/TabMenu').(React),
  Text: require('./components/Text').(React),
  Toast: require('./components/Toast').(React),
  ToastItem: require('./components/ToastItem').(React),
  ToolBar:  require('./components/ToolBar').(React),
};
