'use strict';


module.exports = {
  // React framework
  React: require('react/addons'),

  // Essence components
  AppBar: require('./components/AppBar'),
  BottomSheets: require('./components/BottomSheets'),
  BottomSheetsItem: require('./components/BottomSheetsItem'),
  Btn: require('./components/Btn'),
  BtnItem: require('./components/BtnItem'),
  Block: require('./components/Block'),
  Card: require('./components/Card'),
  CardItem: require('./components/CardItem'),
  CardItemHeader: require('./components/CardItemHeader'),
  CardItemContent: require('./components/CardItemContent'),
  CardItemFooter: require('./components/CardItemFooter'),
  Chip: require('./components/Chip'),
  ChipItem: require('./components/ChipItem'),
  DatePicker: require('./components/DatePicker'),
  DatePickerItem: require('./components/DatePickerItem'),
  DatePickerHeader: require('./components/DatePickerHeader'),
  DatePickerHeaderDay: require('./components/DatePickerHeaderDay'),
  DatePickerHeaderDate: require('./components/DatePickerHeaderDate'),
  DatePickerContent: require('./components/DatePickerContent'),
  DatePickerFooter: require('./components/DatePickerFooter'),
  Dialog: require('./components/Dialog'),
  DialogItem: require('./components/DialogItem'),
  DialogItemHeader: require('./components/DialogItemHeader'),
  DialogItemContent: require('./components/DialogItemContent'),
  DialogItemFooter: require('./components/DialogItemFooter'),
  Divider: require('./components/Divider'),
  Icon: require('./components/Icon'),
  Image: require('./components/Image'),
  Input: require('./components/Input'),
  InputItem: require('./components/InputItem'),
  List: require('./components/List'),
  ListItem: require('./components/ListItem'),
  Menu: require('./components/Menu'),
  MenuItem: require('./components/MenuItem'),
  Navigation: require('./components/Navigation'),
  Paper: require('./components/Paper'),
  PaperItem: require('./components/PaperItem'),
  Progress: require('./components/Progress'),
  Slider: require('./components/Slider'),
  SliderItem: require('./components/SliderItem'),
  Snackbar: require('./components/Snackbar'),
  SnackbarItem: require('./components/SnackbarItem'),
  Switch: require('./components/Switch'),
  SwitchItem: require('./components/SwitchItem'),
  TabItem: require('./components/TabItem'),
  TabMenu: require('./components/TabMenu'),
  Text: require('./components/Text'),
  Toast: require('./components/Toast'),
  ToastItem: require('./components/ToastItem'),
  ToolBar:  require('./components/ToolBar'),

  // Essence utils
  BackgroundColor:  require('./utils/BackgroundColor'),
  ClassNames:  require('./utils/ClassNames'),
  ClickPosition:  require('./utils/ClickPosition'),
  DateFormat:  require('./utils/DateFormat'),
  Mobile:  require('./utils/Mobile'),
  Position:  require('./utils/Position'),
  PositionHorizontal:  require('./utils/PositionHorizontal'),
  PubSub:  require('./utils/PubSub'),
};